Repository saeeddhqan/Maryam, pull requests merged in 2021-03, with the labels that each got.

#38 Replace "type() is" with "isinstance"
  core/framework.py
  core/util/keywords.py
  core/util/web_scrap.py
  modules/footprint/crawl_pages.py
  modules/footprint/interest_files.py
  modules/osint/crawler.py
  modules/osint/social_nets.py
  modules/search/facebook.py
  modules/search/instagram.py
  modules/search/linkedin.py
  modules/search/twitter.py
Labels: bug

#36 Stackoverflow module added in search
  modules/search/stackoverflow.py
Labels: enhancement

#43 Add reverse dns search option
  modules/osint/dns_search.py
Labels: enhancement

#51 filter google search links
  core/util/google.py
Labels: bug, help wanted

#50 Added Search/duckduckgo Module
  core/base.py
  core/framework.py
  core/module.py
  core/util/duckduckgo.py
  modules/search/duckduckgo.py
Labels: enhancement

#65 Cve module
  modules/osint/cve_search.py
Labels: enhancement, help wanted

#79 Added pwned email check module and prestashop CMS detection util function
  core/util/cms_identify.py
  modules/osint/email_pwned.py
  requirements
Labels: enhancement, help wanted

#100 added trello module for issue #99
  modules/search/trello.py
Labels: approved
